Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: IGW

  VPCGatewayAttach:
    Properties:
      InternetGatewayId:
        Ref: InternetGateway
      VpcId:
        Ref: VPC
    Type: AWS::EC2::VPCGatewayAttachment

  PrivateRouteTable:
    Properties:
      Tags:
        - Key: Name
          Value: Route Table for Private subnet
      VpcId:
        Ref: VPC
    Type: AWS::EC2::RouteTable

  PublicRouteTable:
    Properties:
      Tags:
        - Key: Name
          Value: Route Table for Public subnet
      VpcId:
        Ref: VPC
    Type: AWS::EC2::RouteTable

  RouteToInternet:
    DependsOn: VPCGatewayAttach
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
        Ref: PublicRouteTable
    Type: AWS::EC2::Route

  PublicSubnet1:
    Properties:
      AvailabilityZone: ap-southeast-1a
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public Subnet 1
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet

  PublicSubnet2:
    Properties:
      AvailabilityZone: ap-southeast-1b
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public Subnet 2
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet

  PublicSubnet3:
    Properties:
      AvailabilityZone: ap-southeast-1c
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public Subnet 3
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet

  Public1InternetRouteTable:
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: PublicSubnet1
    Type: AWS::EC2::SubnetRouteTableAssociation

  Public2InternetRouteTable:
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: PublicSubnet2
    Type: AWS::EC2::SubnetRouteTableAssociation

  Public3InternetRouteTable:
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: PublicSubnet3
    Type: AWS::EC2::SubnetRouteTableAssociation

  PrivateSubnet1:
    Properties:
      AvailabilityZone: ap-southeast-1a
      CidrBlock: 10.0.3.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Private Subnet 1
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet

  PrivateSubnet2:
    Properties:
      AvailabilityZone: ap-southeast-1b
      CidrBlock: 10.0.4.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Private Subnet 2
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet

  PrivateSubnet3:
    Properties:
      AvailabilityZone: ap-southeast-1c
      CidrBlock: 10.0.5.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Private Subnet 3
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet

  Private1RouteTableAttach:
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: PrivateSubnet1
    Type: AWS::EC2::SubnetRouteTableAssociation

  Private2RouteTableAttach:
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: PrivateSubnet2
    Type: AWS::EC2::SubnetRouteTableAssociation

  Private3RouteTableAttach:
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: PrivateSubnet3
    Type: AWS::EC2::SubnetRouteTableAssociation

  SGforVPC:
    Properties:
      GroupDescription: Security group for VPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: SG for
          IpProtocol: -1
      VpcId:
        Ref: VPC
    Type: AWS::EC2::SecurityGroup

Outputs:
  VPC:
    Description: Environment VPC
    Value: !Ref VPC
  PublicSubnet1:
    Description: Public Subnet 1
    Value: !Ref PublicSubnet1
  PublicSubnet2:
    Description: Public Subnet 2
    Value: !Ref PublicSubnet2
  PublicSubnet3:
    Description: Public Subnet 3
    Value: !Ref PublicSubnet3
  PrivateSubnet1:
    Description: Private Subnet 1
    Value: !Ref PrivateSubnet1
  PrivateSubnet2:
    Description: Private Subnet 2
    Value: !Ref PrivateSubnet2
  PrivateSubnet3:
    Description: Private Subnet 3
    Value: !Ref PrivateSubnet3
  SGfor:
    Description: Security Group for VPC
    Value: !Ref SGforVPC
  PrivateRouteTable:
    Description: Private route table
    Value: !Ref PrivateRouteTable
